/* Database schema to keep the structure of entire database. */

 create table owners (
 id int generated always as identity,
 full_name varchar(100),
 age int,
 primary key (id)
);

create table species (
 id int generated always as identity,
 name varchar (50),
 primary key (id)
);

Ensure the field is not null.
alter table if exists animals alter column id set not null;
Put the value autogenerated.
alter table if exists animals alter column id add generated always as identity;
ALTER TABLE IF EXISTS public.animals
    ADD CONSTRAINT id_pk PRIMARY KEY (id);



ALTER TABLE IF EXISTS animals DROP COLUMN IF EXISTS species;
ALTER TABLE IF EXISTS animals ADD COLUMN species_id int;
ALTER TABLE IF EXISTS animals ADD COLUMN owner_id int


ALTER TABLE IF EXISTS animals
    ADD CONSTRAINT fk_species FOREIGN KEY (species_id)
    REFERENCES species (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS fki_fk_species
    ON public.animals(species_id);


ALTER TABLE IF EXISTS animals
    ADD CONSTRAINT fk_owner FOREIGN KEY (owner_id)
    REFERENCES owners (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS fki_fk_owner
    ON public.animals(owner_id);
