/* Database schema to keep the structure of entire database. */
/* Database schema to keep the structure of entire database. */


create table animals (
 id int,
 name varchar(50),
 date_of_birth date,
 escape_attempts int,
 neutered boolean,
 weigth_kg decimal
 );

/* Database schema to keep the structure of entire database. */


 alter table animals add species varchar null;


 create table owners (
 id int generated always as identity,
 full_name varchar(100),
 age int,
 primary key (id)
);

create table species (
 id int generated always as identity,
 name varchar (50),
 primary key (id)
);

Ensure the field is not null.
alter table if exists animals alter column id set not null;
Put the value autogenerated.
alter table if exists animals alter column id add generated always as identity;
ALTER TABLE IF EXISTS public.animals
    ADD CONSTRAINT id_pk PRIMARY KEY (id);



ALTER TABLE IF EXISTS animals DROP COLUMN IF EXISTS species;
ALTER TABLE IF EXISTS animals ADD COLUMN species_id int;
ALTER TABLE IF EXISTS animals ADD COLUMN owner_id int


ALTER TABLE IF EXISTS animals
    ADD CONSTRAINT fk_species FOREIGN KEY (species_id)
    REFERENCES species (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS fki_fk_species
    ON public.animals(species_id);


ALTER TABLE IF EXISTS animals
    ADD CONSTRAINT fk_owner FOREIGN KEY (owner_id)
    REFERENCES owners (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS fki_fk_owner
    ON public.animals(owner_id);
    
CREATE TABLE  species (
 id int GENERATED ALWAYS AS IDENTITY,
 name varchar (50),
 primary key (id)
);

Ensure the field IS NOT null.
ALTER TABLE if exists animals ALTER column id SET NOT  null;
Put the value autogenerated.
ALTER TABLE if exists animals ALTER column id add GENERATED ALWAYS AS IDENTITY;
ALTER TABLE IF EXISTS public.animals
    ADD CONSTRAINT id_pk PRIMARY KEY (id);



ALTER TABLE IF EXISTS animals DROP COLUMN IF EXISTS species;
ALTER TABLE IF EXISTS animals ADD COLUMN species_id int;
ALTER TABLE IF EXISTS animals ADD COLUMN owner_id int


ALTER TABLE IF EXISTS animals
    ADD CONSTRAINT fk_species FOREIGN KEY (species_id)
    REFERENCES species (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS fki_fk_species
    ON public.animals(species_id);


 CREATE TABLE vets(
 id int GENERATED ALWAYS AS IDENTITY,
 name varchar (100),
 age int,
 date_of_graduation date,
 primary key (id));


CREATE TABLE specializations(
 species_id int,
 vets_id int,
 PRIMARY KEY (species_id,vets_id));

ALTER TABLE public.specializations ADD CONSTRAINT specializations_fk FOREIGN KEY (species_id) REFERENCES public.species(id);
ALTER TABLE public.specializations ADD CONSTRAINT specializations_fk_1 FOREIGN KEY (vets_id) REFERENCES public.vets(id);


 CREATE TABLE visits (
 animals_id int,
 vets_id int,
 date_of_visits date,
 PRIMARY KEY (animals_id,vets_id,date_of_visits));


ALTER TABLE public.visits ADD CONSTRAINT visits_fk FOREIGN KEY (animals_id) REFERENCES public.animals(id);
ALTER TABLE public.visits ADD CONSTRAINT visits_fk_1 FOREIGN KEY (vets_id) REFERENCES public.vets(id);


